baseURL = 'https://orbis-dei.netlify.app/'
languageCode = 'en-us'
title = 'Orbis Dei'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Saints and Holy Persons'
  identifier = 'holy-persons'
  pageRef = 'tags/holy-persons'
  weight = 10
[[menu.main]]
  name = 'Marian Sites'
  identifier = 'marian-sites'
  pageRef = '/tags/marian-sites'
  weight = 10
